### PR TITLE
Fix BC break impacting versions older than 3.4

### LINKED ISSUE #633: BC Break with versions older than 3.4
It looks like this commit https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/629/commits/e985ef5d53221e5bc14dd83f27dc9a448a692fba introduced BC break for older versions as the `setAlias` method started to return the alias since the 3.4 version.

### PR DESCRIPTION
**Pull request by BboyKeen**
The commit e985ef5 introduced BC break for older versions
as the setAlias method started to return the alias since the 3.4
version so chaining the setPublic() method fail using those
versions

This PR brings back back-compatibility

Fixes #633

### CODE REVIEW

**Comment by XWB** [comment]
Thank you.

File: DependencyInjection/FOSCommentExtension.php [hunk 1]
```diff
@@ -80,9 +80,11 @@ public function load(array $configs, ContainerBuilder $container)
         // TODO: change it if https://github.com/symfony/DoctrineMongoDBBundle/pull/31 is merged
         if ('mongodb' === $config['db_driver']) {
             if (null === $config['model_manager_name']) {
-                $container->setAlias('fos_comment.document_manager', new Alias('doctrine.odm.mongodb.document_manager', false))->setPublic(true);
+                $container->setAlias('fos_comment.document_manager', new Alias('doctrine.odm.mongodb.document_manager', false));
+                $container->getAlias('fos_comment.document_manager')->setPublic(true);
             } else {
-                $container->setAlias('fos_comment.document_manager', new Alias(sprintf('doctrine.odm.%s_mongodb.document_manager', $config['model_manager_name']), false))->setPublic(true);
+                $container->setAlias('fos_comment.document_manager', new Alias(sprintf('doctrine.odm.%s_mongodb.document_manager', $config['model_manager_name']), false));
+                $container->getAlias('fos_comment.document_manager')->setPublic(true);
```
Comment (stof) [inline DependencyInjection/FOSCommentExtension.php]: Why are these aliases set public while the constructor was already setting them as private before (and so they were never public even before the 3.4 migration)

Comment (BboyKeen) [reply DependencyInjection/FOSCommentExtension.php]: That's a good question. I only fixed the bc break introduced by the previous commit without thinking about his relevance.
@XWB, do you have an explanation ?
